import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { Toaster } from "react-hot-toast";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-950 text-gray-200 min-h-full`}

      >
        <Navbar/>
        <main className="container mx-auto px-4 py-8">
        {children}
        <Toaster position="top-center"/>
        </main>
      </body>
    </html>
  );
}
